---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "Hyperprivacy network"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Hyperprivacy network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see org1.yaml and org2.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  eventchannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.hyperprivacy.network.com

    # Required. list of peers from participating orgs
    peers:
      peer0.supervisor.hyperprivacy.network.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer0.provider.hyperprivacy.network.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.iot.hyperprivacy.network.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.enduser.hyperprivacy.network.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - sensors:v0
      - events:v0

#
# list of participating organizations in this network
#
organizations:
  Supervisor:
    mspid: SupervisorMSP

    peers:
      - peer0.supervisor.hyperprivacy.network.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca.supervisor.hyperprivacy.network

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: network/channel/crypto-config/peerOrganizations/supervisor.hyperprivacy.network.com/users/Admin@supervisor.hyperprivacy.network.com/msp/keystore/13aeac1a693e796548751d72f47f8119e5a550328a0a1ae3cbd0d62aea67df59_sk
    signedCert:
      path: network/channel/crypto-config/peerOrganizations/supervisor.hyperprivacy.network.com/users/Admin@supervisor.hyperprivacy.network.com/msp/signcerts/Admin@supervisor.hyperprivacy.network.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  Provider:
    mspid: ProviderMSP
    peers:
      - peer0.provider.hyperprivacy.network.com
    certificateAuthorities:
      - ca.provider.hyperprivacy.network
    adminPrivateKey:
      path: network/channel/crypto-config/peerOrganizations/provider.hyperprivacy.network.com/users/Admin@provider.hyperprivacy.network.com/msp/keystore/361e57c852460086dcc151ef7b2974fc3c03d32ab3216985dc65e898a5ade0ea_sk
    signedCert:
      path: network/channel/crypto-config/peerOrganizations/provider.hyperprivacy.network.com/users/Admin@provider.hyperprivacy.network.com/msp/signcerts/Admin@provider.hyperprivacy.network.com-cert.pem

  Iot:
    mspid: IotMSP
    peers:
      - peer0.iot.hyperprivacy.network.com
    certificateAuthorities:
      - ca.iot.hyperprivacy.network
    adminPrivateKey:
      path: network/channel/crypto-config/peerOrganizations/iot.hyperprivacy.network.com/users/Admin@iot.hyperprivacy.network.com/msp/keystore/89f316539d47d407b2cce854702f2e9a32dd0cfc3b312e1cc9edca15a864c04a_sk
    signedCert:
      path: network/channel/crypto-config/peerOrganizations/iot.hyperprivacy.network.com/users/Admin@iot.hyperprivacy.network.com/msp/signcerts/Admin@iot.hyperprivacy.network.com-cert.pem

  EndUser:
    mspid: EndUserMSP
    peers:
      - peer0.enduser.hyperprivacy.network.com
    certificateAuthorities:
      - ca.enduser.hyperprivacy.network
    adminPrivateKey:
      path: network/channel/crypto-config/peerOrganizations/enduser.hyperprivacy.network.com/users/Admin@enduser.hyperprivacy.network.com/msp/keystore/262ca77db39214a28fca30ae7d259f48b44a2e09be061eb7808254dd2c0039ca_sk
    signedCert:
      path: network/channel/crypto-config/peerOrganizations/enduser.hyperprivacy.network.com/users/Admin@enduser.hyperprivacy.network.com/msp/signcerts/Admin@enduser.hyperprivacy.network.com-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  orderer.hyperprivacy.network.com:
    url: grpc://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: orderer.hyperprivacy.network.com

    tlsCACerts:
      path: network/channel/crypto-config/ordererOrganizations/orderer.hyperprivacy.network.com/orderers/orderer.orderer.hyperprivacy.network.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.supervisor.hyperprivacy.network.com:
    # this URL is used to send endorsement and query requests
    url: grpc://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer0.regulator.hyperprivacy.network.com
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/supervisor.hyperprivacy.network.com/peers/peer0.supervisor.hyperprivacy.network.com/tls/ca.crt

  peer0.provider.hyperprivacy.network.com:
    url: grpc://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer0.provider.hyperprivacy.network.com
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/provider.hyperprivacy.network.com/peers/peer0.provider.hyperprivacy.network.com/tls/ca.crt

  peer0.iot.hyperprivacy.network.com:
    url: grpc://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.iot.hyperprivacy.network.com
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/iot.hyperprivacy.network.com/peers/peer0.iot.hyperprivacy.network.com/tls/ca.crt

  peer0.enduser.hyperprivacy.network.com:
    url: grpc://localhost:10051
    grpcOptions:
      ssl-target-name-override: peer0.enduser.hyperprivacy.network.com
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/enduser.hyperprivacy.network.com/peers/peer0.enduser.hyperprivacy.network.com/tls/ca.crt



#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca.supervisor.hyperprivacy.network:
    url: http://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/supervisor.hyperprivacy.network.com/ca/ca.supervisor.hyperprivacy.network.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: supervisor_admin
        enrollSecret: supervisor2019
    # [Optional] The optional name of the CA.
    caName: ca.enduser.hyperprivacy.network

  ca.provider.hyperprivacy.network:
    url: http://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/provider.hyperprivacy.network.com/ca/ca.provider.hyperprivacy.network.com-cert.pem
    registrar:
      - enrollId: provider_admin
        enrollSecret: provider2019
    # [Optional] The optional name of the CA.
    caName: ca.provider.hyperprivacy.network

  ca.iot.hyperprivacy.network:
    url: http://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/iot.hyperprivacy.network.com/ca/ca.iot.hyperprivacy.network.com-cert.pem
    registrar:
      - enrollId: iot_admin
        enrollSecret: iot2019
    # [Optional] The optional name of the CA.
    caName: ca.iot.hyperprivacy.network

  ca.enduser.hyperprivacy.network:
    url: http://localhost:10054
    httpOptions:
      verify: false
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/enduser.hyperprivacy.network.com/ca/ca.enduser.hyperprivacy.network.com-cert.pem
    registrar:
      - enrollId: enduser_admin
        enrollSecret: enduser2019
    # [Optional] The optional name of the CA.
    caName: ca.enduser.hyperprivacy.network