NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.supervisor.hyperprivacy.network.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.supervisor.hyperprivacy.network.com-cert.pem
    OrganizationalUnitIdentifier: peer
