---
#
# The network connection profile provides client applications the information about the target
# blockchain network that are necessary for the applications to interact with it. These are all
# knowledge that must be acquired from out-of-band sources. This file provides such a source.
#
name: "Iot"

#
# Any properties with an "x-" prefix will be treated as application-specific, exactly like how naming
# in HTTP headers or swagger properties work. The SDK will simply ignore these fields and leave
# them for the applications to process. This is a mechanism for different components of an application
# to exchange information that are not part of the standard schema described below. In particular,
# the "x-type" property with the "hlfv1" value example below is used by Hyperledger Composer to
# determine the type of Fabric networks (v0.6 vs. v1.0) it needs to work with.
#
x-type: "hlfv1"

#
# Describe what the target network is/does.
#
description: "Hyperprivacy network"

#
# Schema version of the content. Used by the SDK to apply the corresponding parsing rules.
#
version: "1.0"

#
# The client section will be added on a per org basis see org1.yaml and org2.yaml
#
#client:

#
# [Optional]. But most apps would have this section so that channel objects can be constructed
# based on the content below. If an app is creating channels, then it likely will not need this
# section.
#
channels:
  # name of the channel
  eventchannel:
    # Required. list of orderers designated by the application to use for transactions on this
    # channel. This list can be a result of access control ("org1" can only access "ordererA"), or
    # operational decisions to share loads from applications among the orderers.  The values must
    # be "names" of orgs defined under "organizations/peers"
    orderers:
      - orderer.hyperprivacy.network

    # Required. list of peers from participating orgs
    peers:
      peer0.regulator.iot-blockchain.com:
        # [Optional]. will this peer be sent transaction proposals for endorsement? The peer must
        # have the chaincode installed. The app can also use this property to decide which peers
        # to send the chaincode install request. Default: true
        endorsingPeer: true

        # [Optional]. will this peer be sent query proposals? The peer must have the chaincode
        # installed. The app can also use this property to decide which peers to send the
        # chaincode install request. Default: true
        chaincodeQuery: true

        # [Optional]. will this peer be sent query proposals that do not require chaincodes, like
        # queryBlock(), queryTransaction(), etc. Default: true
        ledgerQuery: true

        # [Optional]. will this peer be the target of the SDK's listener registration? All peers can
        # produce events but the app typically only needs to connect to one to listen to events.
        # Default: true
        eventSource: true

      peer0.provider.iot-blockchain.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.iot.iot-blockchain.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

      peer0.enduser.iot-blockchain.com:
        endorsingPeer: true
        chaincodeQuery: true
        ledgerQuery: true
        eventSource: true

    # [Optional]. what chaincodes are expected to exist on this channel? The application can use
    # this information to validate that the target peers are in the expected state by comparing
    # this list with the query results of getInstalledChaincodes() and getInstantiatedChaincodes()
    chaincodes:
      # the format follows the "cannonical name" of chaincodes by fabric code
      - sensors:v0

#
# list of participating organizations in this network
#
organizations:
  Regulator:
    mspid: RegulatorMSP

    peers:
      - peer0.regulator.iot-blockchain.com

    # [Optional]. Certificate Authorities issue certificates for identification purposes in a Fabric based
    # network. Typically certificates provisioning is done in a separate process outside of the
    # runtime network. Fabric-CA is a special certificate authority that provides a REST APIs for
    # dynamic certificate management (enroll, revoke, re-enroll). The following section is only for
    # Fabric-CA servers.
    certificateAuthorities:
      - ca-regulator

    # [Optional]. If the application is going to make requests that are reserved to organization
    # administrators, including creating/updating channels, installing/instantiating chaincodes, it
    # must have access to the admin identity represented by the private key and signing certificate.
    # Both properties can be the PEM string or local path to the PEM file. Note that this is mainly for
    # convenience in development mode, production systems should not expose sensitive information
    # this way. The SDK should allow applications to set the org admin identity via APIs, and only use
    # this route as an alternative when it exists.
    adminPrivateKey:
      path: network/channel/crypto-config/peerOrganizations/regulator.iot-blockchain.com/users/Admin@regulator.iot-blockchain.com/msp/keystore/ac23fc523003296436b829acd964bea8b8dff065053e285e6ca31adeeb3a0215_sk
    signedCert:
      path: network/channel/crypto-config/peerOrganizations/regulator.iot-blockchain.com/users/Admin@regulator.iot-blockchain.com/msp/signcerts/Admin@regulator.iot-blockchain.com-cert.pem

  # the profile will contain public information about organizations other than the one it belongs to.
  # These are necessary information to make transaction lifecycles work, including MSP IDs and
  # peers with a public URL to send transaction proposals. The file will not contain private
  # information reserved for members of the organization, such as admin key and certificate,
  # fabric-ca registrar enroll ID and secret, etc.
  Provider:
    mspid: ProviderMSP
    peers:
      - peer0.provider.iot-blockchain.com
    certificateAuthorities:
      - ca-provider
    adminPrivateKey:
      path: network/channel/crypto-config/peerOrganizations/provider.iot-blockchain.com/users/Admin@provider.iot-blockchain.com/msp/keystore/09a6691580a54161b0c0278ac24747490a3e024792756fc13524ac962d88a4ce_sk
    signedCert:
      path: network/channel/crypto-config/peerOrganizations/provider.iot-blockchain.com/users/Admin@provider.iot-blockchain.com/msp/signcerts/Admin@provider.iot-blockchain.com-cert.pem

  Iot:
    mspid: IotMSP
    peers:
      - peer0.iot.iot-blockchain.com
    certificateAuthorities:
      - ca-iot
    adminPrivateKey:
      path: network/channel/crypto-config/peerOrganizations/iot.iot-blockchain.com/users/Admin@iot.iot-blockchain.com/msp/keystore/0ba4980e043e4e0f20c13fa7164d06a332d1a7b44979e9cf82af87c320f009bf_sk
    signedCert:
      path: network/channel/crypto-config/peerOrganizations/iot.iot-blockchain.com/users/Admin@iot.iot-blockchain.com/msp/signcerts/Admin@iot.iot-blockchain.com-cert.pem

  EndUser:
    mspid: EndUserMSP
    peers:
      - peer0.enduser.iot-blockchain.com
    certificateAuthorities:
      - ca-enduser
    adminPrivateKey:
      path: network/channel/crypto-config/peerOrganizations/enduser.iot-blockchain.com/users/Admin@enduser.iot-blockchain.com/msp/keystore/820ced519d1cb342d65ba2a6a6b4238d35d75c1a137ad6e76b777cc14c35c25c_sk
    signedCert:
      path: network/channel/crypto-config/peerOrganizations/enduser.iot-blockchain.com/users/Admin@enduser.iot-blockchain.com/msp/signcerts/Admin@enduser.iot-blockchain.com-cert.pem

#
# List of orderers to send transaction and channel create/update requests to. For the time
# being only one orderer is needed. If more than one is defined, which one get used by the
# SDK is implementation specific. Consult each SDK's documentation for its handling of orderers.
#
orderers:
  infodomorderer.iot-blockchain.com:
    url: grpc://localhost:7050

    # these are standard properties defined by the gRPC library
    # they will be passed in as-is to gRPC client constructor
    grpcOptions:
      ssl-target-name-override: infodomorderer.iot-blockchain.com

    tlsCACerts:
      path: network/channel/crypto-config/ordererOrganizations/infodomorderer.iot-blockchain.com/orderers/infodomorderer.infodomorderer.iot-blockchain.com/tls/ca.crt

#
# List of peers to send various requests to, including endorsement, query
# and event listener registration.
#
peers:
  peer0.regulator.iot-blockchain.com:
    # this URL is used to send endorsement and query requests
    url: grpc://localhost:7051

    grpcOptions:
      ssl-target-name-override: peer0.regulator.iot-blockchain.com
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/regulator.iot-blockchain.com/peers/peer0.regulator.iot-blockchain.com/tls/ca.crt

  peer0.provider.iot-blockchain.com:
    url: grpc://localhost:8051
    grpcOptions:
      ssl-target-name-override: peer0.provider.iot-blockchain.com
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/provider.iot-blockchain.com/peers/peer0.provider.iot-blockchain.com/tls/ca.crt

  peer0.iot.iot-blockchain.com:
    url: grpc://localhost:9051
    grpcOptions:
      ssl-target-name-override: peer0.iot.iot-blockchain.com
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/iot.iot-blockchain.com/peers/peer0.iot.iot-blockchain.com/tls/ca.crt

  peer0.enduser.iot-blockchain.com:
    url: grpc://localhost:10051
    grpcOptions:
      ssl-target-name-override: peer0.enduser.iot-blockchain.com
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/enduser.iot-blockchain.com/peers/peer0.enduser.iot-blockchain.com/tls/ca.crt



#
# Fabric-CA is a special kind of Certificate Authority provided by Hyperledger Fabric which allows
# certificate management to be done via REST APIs. Application may choose to use a standard
# Certificate Authority instead of Fabric-CA, in which case this section would not be specified.
#
certificateAuthorities:
  ca-regulator:
    url: http://localhost:7054
    # the properties specified under this object are passed to the 'http' client verbatim when
    # making the request to the Fabric-CA server
    httpOptions:
      verify: false
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/regulator.iot-blockchain.com/ca/ca.regulator.iot-blockchain.com-cert.pem

    # Fabric-CA supports dynamic user enrollment via REST APIs. A "root" user, a.k.a registrar, is
    # needed to enroll and invoke new users.
    registrar:
      - enrollId: regulator_admin
        enrollSecret: regulator2019
    # [Optional] The optional name of the CA.
    caName: ca-regulator

  ca-provider:
    url: http://localhost:8054
    httpOptions:
      verify: false
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/provider.iot-blockchain.com/ca/ca.provider.iot-blockchain.com-cert.pem
    registrar:
      - enrollId: provider_admin
        enrollSecret: provider2019
    # [Optional] The optional name of the CA.
    caName: ca-provider

  ca-iot:
    url: http://localhost:9054
    httpOptions:
      verify: false
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/iot.iot-blockchain.com/ca/ca.iot.iot-blockchain.com-cert.pem
    registrar:
      - enrollId: iot_admin
        enrollSecret: iot2019
    # [Optional] The optional name of the CA.
    caName: ca-iot

  ca-enduser:
    url: http://localhost:10054
    httpOptions:
      verify: false
    tlsCACerts:
      path: network/channel/crypto-config/peerOrganizations/enduser.iot-blockchain.com/ca/ca.enduser.iot-blockchain.com-cert.pem
    registrar:
      - enrollId: enduser_admin
        enrollSecret: enduser2019
    # [Optional] The optional name of the CA.
    caName: ca-enduser